config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  devise_for :users

  resources :projects do 
    resources :rewards, only: [:new, :create, :edit, :update, :destroy]
    resources :pledges
    resources :payments, only: [:new, :create]
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

  extend FriendlyId
  friendly_id :uuid

  belongs_to :user
  belongs_to :reward

  before_validation     :generate_uuid!, :on => :create
  validates_presence_of :name, :address, :city, :country, :postal_code, :amount, :user_id
  after_create          :check_if_funded

  def charge!
    return false if self.charged? || !self.project.funded?
    id = user.customer_id
    if id.present? && @customer = Braintree::Customer.find(id)
      result = Braintree::Transaction.sale(
        :customer_id => @customer_id,
        :amount => self.amount
      )
      if result.success?
        self.charged!
      else
        self.void!
      end
    end
  end

  def charged?
    status == "charged"
  end

  def failed?
    status == "failed"
  end

  def pending?
    status == "pending"
  end

  def charged!
    update(status: "charged")
  end

  def void!
    update(status: "void")
  end

  private

  def generate_uuid!
    begin
      self.uuid = SecureRandom.hex(16)      
    end while Pledge.find_by(:uuid => self.uuid).present?
  end

  def check_if_funded
    project.funded! if project.total_backed_amount >= project.goal
  end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project
  before_action :set_reward

  def index
    authorize! :manage, @project
    @pledges = @project.pledges
    respond_to do |format|
      format.html 
    end
  end

  def new
    @pledge = current_user.pledges.build
    @rewards = @project.rewards
    respond_to do |format|
      format.html
    end
  end

  private

    def set_project
      @project = Project.friendly.find(params[:project_id])
    end

    def set_reward
      @reward = @project.rewards.find_by_id(params[:reward_id])      
    end

end

app/helpers/pledges_helper.rb
module PledgesHelper
  def pledge_radio_button(reward)
    text =  " $#{reward.value}"
    text += "<p>#{reward.description}</p>"
    text += "<p><strong>Estimated Delivery: </strong>#{reward.estimated_delivery}</p>"
    text.html_safe
  end
end

app/views/pledges/_form.html.erb
<%= simple_form_for @pledge, url: new_project_payment_path(@project), method: :get do |f| %>

	<h1>Alrighty!</h1>
	<h2>Enter your pledge amount</h2>
	
	<fieldset>
		<%= f.input :amount, placeholder: "Enter your pledge amount:", input_html: { value: @reward.try(:value), required: true} %>
	</fieldset>
	<br>
	<fieldset>
		<legend>Select your reward</legend>
		<%= f.collection_radio_buttons(:reward_id, @rewards, :id, :id, :checked => @reward.try(:id)) do |b| %>
			<% b.label(:"data-value" => b.value) { b.radio_button + pledge_radio_button(b.object) }  %>
		<% end %>
	</fieldset>

	<%= f.submit "Continue to next step", class: "btn btn-success btn-md pull-right" %>
	<div class="clearfix"></div>

<% end %>

app/views/pledges/_pledge.html.erb
 <tr>
	<th scope="row"><%= pledge.id %></th>
	<td><%= link_to pledge.project.name, project_path(pledge.project) %></td>
	<td><%= number_to_currency(pledge.amount, unit: "$") %></td>
	<td><%= pledge.estimated_delivery %></td>
</tr>

app/views/pledges/_table.html.erb
<table class="table table-hover">

	<thead>
		<tr>
			<th>#</th>
			<th>Project</th>
			<th>Pledge</th>
			<th>Estimated Delivery</th>
		</tr>
	</thead>

	<tbody>
		<% if pledges.any? %>
			<% pledges.each do |pledge| %>
				<%= render 'pledge', pledge: pledge %>
			<% end %>
		<% else %>
			<tr>
				<td colspan="4">No pledges available</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/pledges/index.html.erb
<div class="project-intro">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive">
					<%= render 'pledges/table', pledges: @pledges %>
				</div>
			</div>
		</div>	
	</div>	
</div>

app/views/pledges/new.html.erb
<div class="project-intro">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="project-title text-center"><a href=""><%= @project.name %></a></h2>
				<div class="pledge-box">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>