config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  devise_for :users

  resources :projects do 
    resources :rewards, only: [:new, :create, :edit, :update, :destroy]
    resources :pledges
    resources :payments, only: [:new, :create]
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                :integer          not null, primary key
#  user_id           :integer
#  name              :string
#  short_description :text
#  description       :text
#  image_url         :string
#  status            :string           default("pending")
#  goal              :decimal(8, 2)
#  expiration_date   :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Project < ActiveRecord::Base
	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

	belongs_to :user
	has_many :rewards

	before_validation :start_project, :on => :create
	validates :name, :short_description, :description, :image_url, :expiration_date, :goal, presence: true
 	after_create :charge_backers_if_funded
 	#before_validation :charge_backers_if_funded, :on => :create

	def pledges
		rewards.flat_map(&:pledges)
	end

	def total_backed_amount
		pledges.map(&:amount).inject(0, :+)
	end

	def funding_percentage
		backed = total_backed_amount
		backed.zero? ? 0 : (backed/goal*100).to_f.round
	end

	def days_to_go
		(self.expiration_date.to_date - Date.today).to_i
	end

	def funded?
		status == "funded"
	end

	def expired?
		status == "expired"
	end

	def canceled?
		status == "canceled"
	end

	def funded!
		update(status: "funded")
	end

	def expired!
		update(status: "expired")
		void_pledges
	end

	def canceled!
		update(status: "canceled")
		void_pledges
	end


	private


	def void_pledges
		self.pledges.each { |p| p.void! }
	end

	def start_project
		self.expiration_date = 1.month.from_now
	end

	def charge_backers_if_funded
		ChargeBackersJob.set(wait_until: self.expiration_date).perform_later self.id
	end

	def slug_candidates
		[
			:name,
			[:name, :created_at]
	   ]
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_project, only: [:show, :edit, :update, :destroy]
	before_action :set_pledges, only: [:show] 
	load_and_authorize_resource
	
	def index
		@projects = Project.all
		@displayed_projects = Project.take(4)
	end

	def show
		@rewards = @project.rewards
		@days_to_go = @project.days_to_go
	end

	def new
		@project = Project.new
	end

	def edit
	end

	def create
		@project = current_user.projects.build(project_params)

		respond_to do |format|
			if @project.save
				format.html { redirect_to @project, notice: "Project was succesfully created!"}
				format.json { render :show, status: :ok, location: @project }
			else
				format.html { render :new }
				format.json { render json: @project.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @project.update(project_params)
				format.html { redirect_to @project, notice: "Project was succesfully Update!"}
				format.json { render :show, status: :ok, location: @project }
			else
				format.html { render :edit }
				format.json { render json: @project.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@project.destroy
		respond_to do |format|
				format.html { redirect_to root_path, notice: "Project was succesfully Destroyed!"}
				format.json { head :no_content }
		end
	end



	private

	def set_pledges
		@pledges = @project.pledges
	end

	def set_project
		@project = Project.friendly.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:name, :short_description, :description, :goal, :image_url, :expiration_date)
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def funding_status_message(project)
    case project.status
      when "pending"
        "This project will only be funded if, at least, #{number_to_currency(project.goal, unit: '$')} is pledged by #{project.expiration_date}."
      when "funded"
        "This project will be funded on #{project.expiration_date}."
      when "expired"
        "This project failed to meet the goal."
      when "canceled"
        "This project has been canceled."
    end              
  end

end

app/views/projects/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ol class="carousel-indicators">
      <% projects.count.times do |i| %>
        <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="<%= "active" if i.zero? %>"></li>
      <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% projects.each_with_index do |project, index| %>
      <div class="item <%= "active" if index.zero? %>">
        <img src="<%= project.image_url %>" alt="...">
        <div class="carousel-caption">
          <div class="container">
            <h2><%= project.name %></h2>
            <p><%= project.short_description %></p>
            <%= link_to "View Project", project_path(project), class: "btn btn-success btn-lg" %>    
          </div>
        </div>
      </div>
    <% end %>
  </div>

    <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.input :name %>
	<%= f.input :short_description %>
	<%= f.input :description, as: :wysihtml5 %>
	<%= f.input :goal %>
	<%= f.input :image_url %>
	<div class="actions">
		<%= f.button :submit %>
	</div>
<% end %>

app/views/projects/_project.html.erb
<% funded = project.funding_percentage  %>
<div class="col-md-4 col-sm-6 col-xs-12">
<div class="project-box">
	<%= link_to image_tag(project.image_url, alt: project.name, width: '100%', height: '200px'), project_path(project) %>
<div class="description-box">
	<div class="title">
	<%= link_to project.name, "#" %>
	</div>
	<div class="description">
		<%= project.short_description %>
	</div>
	<div class="project-bar">
		<div class="progress">
			<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= funded %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= funded %>">
				<span class="sr-only"><%= funded %> Complete (Success)</span>
			</div>
		</div>
	</div>

	<div class="stats">
		<ul>
			<li><%= funded %>% <br><span class="label">funded</span></li>
			<li>$<%= project.total_backed_amount  %><br><span class="label">pledged</span></li></li>
			<li><%= project.days_to_go %> <br><span class="label">days to go</span></li></li></li>
		</ul>
	</div>
</div>
</div>
</div>

app/views/projects/_stats.html.erb
<div class="project-stats">
	<div class="row">

		<!-- number of backers -->
		<div class="col-xs-4 col-sm-12">
			<div class="val">
				<%= @pledges.count %>
			</div>
			<div class="lab">
				backers
			</div>
		</div>

		<!-- goal -->
		<div class="col-xs-4 col-sm-12">
			<div class="val">
				<%= number_to_currency(@project.total_backed_amount, unit: "$", precision: 0) %>
			</div>
			<div class="lab">
				pledge of <%= number_to_currency(@project.goal, unit: "$", precision: 0) %> goal
			</div>
		</div>

		<!-- days to go -->
		<div class="col-xs-4 col-sm-12">
			<div class="val">
			    <%= days_to_go %>
			</div>
			<div class="lab">
				days to go
			</div>
		</div>

	</div>
</div>

app/views/projects/edit.html.erb
<div class="container">
	<h1>Editing Project</h1>
	<%= render 'form' %>

	<%= link_to 'Show', @project %>
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<% if @displayed_projects.any? %>

<%= render "carousel", projects: @displayed_projects %>

<div class="container">
	<br><br><br>
	<h3 class="project-subtitle">Our Projects</h3>
	
	<div class="row">
		<%= render @projects %>
	</div>
</div>

<% else %>

<div class="container text-center">
	<br><br><br>
	<h2>Create your first project</h2>
	<%= link_to "Start_project", "#", class: "btn btn-success btn-lg" %>
</div>


<% end %>

app/views/projects/new.html.erb
<div class="container">
	<h1>Create a new Project</h1>
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="project-intro">
	<div class="container">

		<div class="row">
			<div class="col-md-12 text-center">
				<h2 class="project-title"><%= @project.name %></h2>
			</div>	
		</div>

		<div class="row">
			<div class="col-md-8">
				<%= link_to image_tag(@project.image_url, alt: @project.name, widh: '100%'), project_path(@project) %>
			</div>
			<div class="col-md-4">
			<% if can? :manage, @project %>
				<div class="project-mgmt">
					<%= link_to 'Edit',   edit_project_path(@project) %>
					<%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
				</div>
			<% end %>
				<%= render 'stats', project: @project, days_to_go: @days_to_go %>
			<% if can? :manage, @project %>
				<%= link_to 'See project backers', project_pledges_path(@project), class: "btn btn-success btn-lg" %>
			<% else %>
				<%= link_to 'Back this project', new_project_pledge_path(@project), class: "btn btn-success btn-lg" %>
			<% end %>
				<p class="project-time"><%= funding_status_message @project %></p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p class="project-small-description"><%= @project.short_description %></p>
			</div>
		</div>
	</div>
</div>


<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h3 class="project-subtitle">About this project</h3>
			<p><%= raw @project.description %></p>
		</div>
		<div class="col-md-4">
			<p><%= render @rewards %></p>
			<% if can? :manage, @project.rewards.build %>
				<%= link_to 'Add Reward', new_project_reward_path(@project), class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>